spring.application.name=demo
server.port=2627


meta.datasource.jdbc-url=${DB_URL}
meta.datasource.username=${DB_USERNAME}
meta.datasource.password=${DB_PASSWORD}
meta.datasource.driver-class-name=org.postgresql.Driver

aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.bucket-name=${AWS_BUCKET_NAME}
aws.bucket-url=${AWS_BUCKET_URL}